export const dataEcs = [
  {
    ec_id: "000",
    ec_name: "ชนิดผัก",
    ec_min: 0,
    ec_max: 0,
  },
  {
    ec_id: "001",
    ec_name: "กล้วย",
    ec_min: 1.8,
    ec_max: 2.2,
  },
  {
    ec_id: "002",
    ec_name: "กวางตุ้งใบ,กวางตุ้งดอก,ฮ่องเต้",
    ec_min: 1.5,
    ec_max: 2.5,
  },
  {
    ec_id: "003",
    ec_name: "กะหล่ำดอก",
    ec_min: 1.5,
    ec_max: 2.0,
  },
  {
    ec_id: "004",
    ec_name: "กะหล่ำปลี,กะหล่ำดาว",
    ec_min: 2.5,
    ec_max: 3.0,
  },
  {
    ec_id: "004",
    ec_name: "ข้าวโพดหวาน",
    ec_min: 1.6,
    ec_max: 2.4,
  },
  {
    ec_id: "005",
    ec_name: "แครอท",
    ec_min: 1.6,
    ec_max: 2.0,
  },
  {
    ec_id: "006",
    ec_name: "เซอลารี่",
    ec_min: 1.8,
    ec_max: 2.4,
  },
  {
    ec_id: "007",
    ec_name: "แตงกวา",
    ec_min: 1.7,
    ec_max: 2.5,
  },
  {
    ec_id: "008",
    ec_name: "แตงกวาซูกินี",
    ec_min: 1.8,
    ec_max: 2.4,
  },
  {
    ec_id: "009",
    ec_name: "แตงโม",
    ec_min: 1.8,
    ec_max: 2.4,
  },
  {
    ec_id: "010",
    ec_name: "ถั่ว",
    ec_min: 2.0,
    ec_max: 4.0,
  },
  {
    ec_id: "011",
    ec_name: "บลอคเคอรี่",
    ec_min: 2.8,
    ec_max: 3.5,
  },
  {
    ec_id: "012",
    ec_name: "บลูเบอรี่",
    ec_min: 1.8,
    ec_max: 2.0,
  },
  {
    ec_id: "013",
    ec_name: "บาเซิล,โหระพา",
    ec_min: 1.0,
    ec_max: 1.6,
  },
  {
    ec_id: "014",
    ec_name: "บิทรูท",
    ec_min: 1.8,
    ec_max: 5.0,
  },
  {
    ec_id: "015",
    ec_name: "ผักขม",
    ec_min: 1.8,
    ec_max: 2.3,
  },
  {
    ec_id: "016",
    ec_name: "พาสเลย์",
    ec_min: 0.8,
    ec_max: 1.8,
  },
  {
    ec_id: "017",
    ec_name: "ฟักทอง",
    ec_min: 1.8,
    ec_max: 2.4,
  },
  {
    ec_id: "018",
    ec_name: "มะเขือเทศ",
    ec_min: 2.0,
    ec_max: 4.0,
  },
  {
    ec_id: "019",
    ec_name: "มะเขือม่วง",
    ec_min: 2.5,
    ec_max: 3.5,
  },
  {
    ec_id: "020",
    ec_name: "เมล่อน",
    ec_min: 2.0,
    ec_max: 2.5,
  },
  {
    ec_id: "021",
    ec_name: "เรดิส,หัวไชเท้า",
    ec_min: 1.6,
    ec_max: 2.2,
  },
  {
    ec_id: "022",
    ec_name: "วอเตอร์เครส",
    ec_min: 0.4,
    ec_max: 1.6,
  },
  {
    ec_id: "023",
    ec_name: "สตรอเบอรี่",
    ec_min: 1.8,
    ec_max: 2.2,
  },
  {
    ec_id: "024",
    ec_name: "สลัด",
    ec_min: 1.1,
    ec_max: 1.7,
  },
  {
    ec_id: "025",
    ec_name: "สะระแหน่,มิ้น",
    ec_min: 2.0,
    ec_max: 2.4,
  },
  {
    ec_id: "026",
    ec_name: "สับปะรด",
    ec_min: 2.0,
    ec_max: 2.4,
  },
  {
    ec_id: "027",
    ec_name: "เสาวรส",
    ec_min: 1.6,
    ec_max: 2.4,
  },
  {
    ec_id: "028",
    ec_name: "หน่อไม้ฝรั่ง",
    ec_min: 1.4,
    ec_max: 1.8,
  },
  {
    ec_id: "029",
    ec_name: "เอิ้นไดร์,ชิโคลี่",
    ec_min: 2.0,
    ec_max: 2.4,
  },
];
